openapi: 3.0.1
info:
  version: 1.0.1
  title: BankManager
  description: lol api

servers:
  - url: "http://notlocalhost:8080"

paths:
  /user/getdata:
    get:
      tags:
        - user
      description: This is a getdata call
      operationId: getAllBanks
      responses:
        '200':
          description: This is 200 description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JpaBankEntity'
  /user/surname/{surname}:
    get:
      tags:
        - user
      description: This is a getdata call
      operationId: getBanksBySurname
      parameters:
        - name: surname
          in: path
          description: surname variable
          required: true
          style: simple

          schema:
            maxLength: 255
            type: string
      responses:
        '200':
          description: This is 200 description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JpaBankEntity'
  /user/{id}:
    get:
      tags:
        - user
      description: This is a a bank call
      operationId: getBankById
      parameters:
        - name: id
          in: path
          description: id variable
          required: true
          style: simple

          schema:
            maxLength: 255
            type: string
      responses:
        '200':
          description: This is 200 description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JpaBankEntity'
    delete:
      tags:
        - user
      description: This is a bank delete call
      operationId: deleteBankById
      parameters:
        - name: id
          in: path
          description: id variable
          required: true
          style: simple

          schema:
            maxLength: 255
            type: string
      responses:
        '204':
          description: This is 204 description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletedMessage'
  /user/handleBankData:
    post:
      tags:
        - user
      description: This post adds a bank
      operationId: postBank
      summary: Creates a user.
      requestBody:
        required: true
        description: The bank to create.
        content:
          application/json:
            schema:
              type: object
              properties:
                accountNumber:
                  type: string
                surname:
                  type: string
                trust:
                  type: number
                transactionFee:
                  type: integer
      responses:
        '200':
          description: "This is 201created description"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedMessage'
    put:
      tags:
        - user
      description: This post adds a bank
      operationId: putBank
      summary: Creates a user.
      requestBody:
        required: true
        description: The bank to create.
        content:
          application/json:
            schema:
              type: object
              properties:
                accountNumber:
                  type: string
                surname:
                  type: string
                trust:
                  type: number
                transactionFee:
                  type: integer
      responses:
        '200':
          description: "This is 201 created description"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedMessage'

  /ozgur/testEndpoint:
    post:
      tags:
        - ozgur
      description: This is a new endpoint generation test with multiple operations.
      operationId: postOperation
      summary: My summary 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OzgurOperationInput'
      responses:
        '200':
          description: "This response is brought you by Swagger!"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OzgurOperationObject'
    put:
      tags:
        - ozgur
      description: This is a new endpoint generation test with multiple operations.
      operationId: putOperation
      summary: My summary 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OzgurOperationInput'
      responses:
        '200':
          description: "This response is brought you by Swagger!"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OzgurOperationObject'

components:
  schemas:
    OzgurOperationInput:
      type: object
      required:
        - name
      properties:
        name:
          maxLength: 55
          pattern: (.|\s)*\S(.|\s)*
          type: string
    OzgurOperationObject:
      type: object
      properties:
        name:
          maxLength: 55
          pattern: (.|\s)*\S(.|\s)*
          type: string
        message:
          type: string
          maxLength: 255
    JpaBankEntity:
      type: object
      properties:
        accountNumber:
          type: string
          example: sdwd3d32dd
        trust:
          type: number
          example: 3.14
        transactionFee:
          type: integer
          example: 42
        surname:
          type: string
          example: Doe
    CreatedMessage:
      type: object
      properties:
        message:
          type: string
          example: 201created
    DeletedMessage:
      type: object
      properties:
        message:
          type: string
          example: 201created



