
spring:
  application:
    name: ayparDeneme1

  datasource:
    url: jdbc:mysql://localhost:3306/banksdb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

